FROM ubuntu:precise

RUN echo deb http://ppa.launchpad.net/mercurial-ppa/releases/ubuntu precise main > /etc/apt/sources.list.d/mercurial.list
RUN apt-get update -qq
RUN apt-get install -y --force-yes git python-dev build-essential python-pip
RUN apt-get install -y --force-yes mercurial
RUN pip install pip

ADD run.sh /run.sh

ENTRYPOINT ["/run.sh"]

CMD ["tests", "--cov", "repoman"]
