FROM debian:wheezy

RUN apt-get update
RUN apt-get install -y --force-yes -t stable git python-dev build-essential python-pip
RUN apt-get install -y --force-yes mercurial
RUN pip install pip

ADD run.sh /run.sh

ENTRYPOINT ["/run.sh"]

CMD ["tests", "--cov", "repoman"]
