FROM fedora:20

RUN yum -y install mercurial
RUN yum -y install git
# Rawhide libgit packages needed to compile pygit2
RUN yum -y install fedora-release-rawhide
RUN yum -y install --enablerepo=rawhide libgit2 libgit2-devel
RUN yum -y install python2-devel
RUN yum -y install make automake gcc gcc-c++
RUN yum -y install python-pip
RUN pip install pip

ADD run.sh /run.sh

ENTRYPOINT ["/run.sh"]

CMD ["tests", "--cov", "repoman"]
