FROM debian:jessie

RUN apt-get update
RUN apt-get install -y --force-yes mercurial git
RUN apt-get install -y --force-yes python-dev build-essential python-pip
RUN pip install pip

ADD run.sh /run.sh

ENTRYPOINT ["/run.sh"]

CMD ["tests", "--cov", "repoman"]
